services:
  postgres:
    image: postgres:16-alpine
    container_name: backend_learning_postgres
    environment:
      POSTGRES_DB: backend_learning
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: backend_pass
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backend_user -d backend_learning"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
